jwt-token-secret-key: ${jwtTokenSecretKey}
spring:
  datasource:
    url: ${databaseURL}
    username: ${dbUsername}
    password: ${dbPassword}
    platform: postgres
    hikari:
      connection-test-query: SELECT 1

  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: validate

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true