CREATE TABLE book_review (
  id UUID NOT NULL,
  title VARCHAR(255),
  content VARCHAR(255),
  score VARCHAR(255),
  created_at TIMESTAMP WITHOUT TIME ZONE,
  updated_at TIMESTAMP WITHOUT TIME ZONE,
  book_id UUID NOT NULL,
  user_id UUID NOT NULL,
  CONSTRAINT pk_bookreview PRIMARY KEY (id)
);

ALTER TABLE book_review ADD CONSTRAINT FK_BOOKREVIEW_ON_BOOK FOREIGN KEY (book_id) REFERENCES book (id) ON DELETE CASCADE;

ALTER TABLE book_review ADD CONSTRAINT FK_BOOKREVIEW_ON_USER FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE;

