name: API Build

on:
  push:
    paths:
      - "api/**"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to heroku using an action
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bookworld-api"
          heroku_email: "heidichiu1025@gmail.com"
          appdir: "api"
        env:
          HD_GRADLE_TASK: "build"
          HD_SPRING.PROFILES.ACTIVE: "prod"
          HD_databaseURL: "jdbc:postgresql://ec2-54-211-74-66.compute-1.amazonaws.com:5432/d2sbtamnmubkj0"
          HD_dbUsername: ${{secrets.dbUsername}}
          HD_dbPassword: ${{secrets.dbPassword}}
